# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\agregarLibro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(365, 458)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 20, 221, 71))
        self.label.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.leiD = QtWidgets.QLineEdit(Dialog)
        self.leiD.setGeometry(QtCore.QRect(70, 90, 231, 31))
        self.leiD.setObjectName("leiD")
        self.leNombre = QtWidgets.QLineEdit(Dialog)
        self.leNombre.setGeometry(QtCore.QRect(70, 160, 231, 31))
        self.leNombre.setObjectName("leNombre")
        self.leEmail = QtWidgets.QLineEdit(Dialog)
        self.leEmail.setGeometry(QtCore.QRect(70, 230, 231, 31))
        self.leEmail.setObjectName("leEmail")
        self.btnAgregar = QtWidgets.QPushButton(Dialog)
        self.btnAgregar.setGeometry(QtCore.QRect(140, 300, 93, 28))
        self.btnAgregar.setObjectName("btnAgregar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Agregar Usuario"))
        self.leiD.setPlaceholderText(_translate("Dialog", "Ingresa el ID del usuario"))
        self.leNombre.setPlaceholderText(_translate("Dialog", "Ingresa el nombre"))
        self.leEmail.setPlaceholderText(_translate("Dialog", "Ingresa el email"))
        self.btnAgregar.setText(_translate("Dialog", "Agregar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
