# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Home_View.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import images.images


class Ui_Dialog(object):
        def setupUi(self, Dialog):
                Dialog.setObjectName("Dialog")
                Dialog.resize(728, 585)
                self.label_6 = QtWidgets.QLabel(Dialog)
                self.label_6.setGeometry(QtCore.QRect(0, 0, 981, 61))
                self.label_6.setStyleSheet("font: 87 18pt \"Arial Black\";\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.556818, x2:0, y2:0.42, stop:0 rgba(157, 197, 235, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(109, 112, 116);")
                self.label_6.setObjectName("label_6")


                self.label = QtWidgets.QLabel(Dialog)
                self.label.setGeometry(QtCore.QRect(-40, 60, 811, 521))
                self.label.setPixmap(QtGui.QPixmap("images/biblioteca.jpg").scaled(self.label.size(), QtCore.Qt.KeepAspectRatio))
                self.label.setText("")
                self.label.setObjectName("label")
              
                self.btnOpenAddLibro = QtWidgets.QPushButton(Dialog)
                self.btnOpenAddLibro.setGeometry(QtCore.QRect(200, 230, 150, 150))
                self.btnOpenAddLibro.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(30, 41, 255);\n"
"background-color: rgb(100, 149, 237);")
                self.btnOpenAddLibro.setDefault(True)
                self.btnOpenAddLibro.setFlat(False)
                self.btnOpenAddLibro.setObjectName("btnOpenAddLibro")

                self.btnOpenAddUsuario = QtWidgets.QPushButton(Dialog)
                self.btnOpenAddUsuario.setGeometry(QtCore.QRect(400, 230, 150, 150))
                self.btnOpenAddUsuario.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(30, 41, 255);\n"
"background-color: rgb(100, 149, 237);")
                self.btnOpenAddUsuario.setDefault(True)
                self.btnOpenAddUsuario.setFlat(False)
                self.btnOpenAddUsuario.setObjectName("btnOpenAddUsuario")

                self.retranslateUi(Dialog)
                QtCore.QMetaObject.connectSlotsByName(Dialog)

        def retranslateUi(self, Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
                self.label_6.setText(_translate("Dialog", " System to add new books and users "))
                self.btnOpenAddLibro.setText(_translate("Dialog", "Add Book"))
                self.btnOpenAddUsuario.setText(_translate("Dialog", "Add User"))



if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        Dialog.show()
        sys.exit(app.exec_())
